FROM python:3.11-slim

# WORKDIR /notebook
COPY . /app
WORKDIR /app

RUN pip install -e .
# RUN pip install -U "langgraph-cli[inmem]"
EXPOSE 8501

CMD ["python","/app/src/icisk_orchestrator/webapp/launch_webapp.py"]